### ISSUE TITLE
AMD release?

### ISSUE THREAD

**Issue by Sylk** [RavenCommunity/kawpowminer#75]
The docs say to use the amd release, however there is no amd release from what I can see. Please advise.

**Comment by jeroz1** [comment]
`kawpowminer -U ` for NVIDIA
`kawpowminer -G ` for AMD

**Comment by Sylk** [comment]
@jeroz1 attempting to run it like this now:
`kawpowminer -G stratum+tcp://RGfSEQtcfJf1kMZ1eu6JJt9vfFmScSnVQb.slamJam@stratum-ravencoin.flypool.org:3333`

Getting `The application was unable to start correctly (0xc000007b). Click OK to close the application.`

**Comment by Sylk** [comment]
@jeroz1 attempting to run it like this now:
kawpowminer -G stratum+tcp://address.workerName@stratum-ravencoin.flypool.org:3333

Getting The application was unable to start correctly (0xc000007b). Click OK to close the application.

**Comment by jeroz1** [comment]
try `kawpowminer -U -P stratum+tcp://address.workerName@stratum-ravencoin.flypool.org:3333`

and oh, that's a common error that hasn't been fixed yet :(

**Comment by SergeantSerk** [comment]
Just as a note, I'm getting `The code execution cannot proceed because nvcuda.dll was not found.` error. I'm curious to know, do I have to install CUDA drivers regardless since I have an AMD card and the `-G` changes nothing for me?

I ran the exact command that was supplied in the previous comment but with my own address and worker name.

**Comment by fdoving** [comment]
Building opencl-only for windows right now.

**Comment by fdoving** [comment]
OpenCL-only binaries built for 1.2.4, windows and ubuntu20:

https://github.com/RavenCommunity/kawpowminer/releases/tag/1.2.4
